name: Deploy Helm Chart to AKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Azure CLI
      uses: azure/CLI@v1
      with:
        azcliversion: '2.0.72'

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Initialize Terraform
      working-directory: ./terraform
      run: terraform init

    - name: Plan Terraform
      working-directory: ./terraform
      run: terraform plan -var="acr_server=${{ secrets.ACR_SERVER }}" \
                          -var="acr_server_subscription=${{ secrets.ACR_SERVER_SUBSCRIPTION }}" \
                          -var="source_acr_client_id=${{ secrets.SOURCE_ACR_CLIENT_ID }}" \
                          -var="source_acr_client_secret=${{ secrets.SOURCE_ACR_CLIENT_SECRET }}" \
                          -var="source_acr_server=${{ secrets.SOURCE_ACR_SERVER }}" \
                          -var="charts=[{
                              chart_name = \"ping\",
                              chart_namespace = \"default\",
                              chart_repository = \"ping\",
                              chart_version = \"1.0.0\",
                              values = [
                                {
                                  name = \"replicaCount\",
                                  value = \"1\"
                                }
                              ],
                              sensitive_values = []
                          }]"

    - name: Apply Terraform
      working-directory: ./terraform
      run: terraform apply -auto-approve -var="acr_server=${{ secrets.ACR_SERVER }}" \
                           -var="acr_server_subscription=${{ secrets.ACR_SERVER_SUBSCRIPTION }}" \
                           -var="source_acr_client_id=${{ secrets.SOURCE_ACR_CLIENT_ID }}" \
                           -var="source_acr_client_secret=${{ secrets.SOURCE_ACR_CLIENT_SECRET }}" \
                           -var="source_acr_server=${{ secrets.SOURCE_ACR_SERVER }}" \
                           -var="charts=[{
                              chart_name = \"ping\",
                              chart_namespace = \"default\",
                              chart_repository = \"ping\",
                              chart_version = \"1.0.0\",
                              values = [
                                {
                                  name = \"replicaCount\",
                                  value = \"1\"
                                }
                              ],
                              sensitive_values = []
                           }]"

    - name: Get AKS Credentials
      run: |
        az aks get-credentials --resource-group ${{ secrets.RESOURCE_GROUP }} --name ${{ secrets.CLUSTER_NAME }}

    - name: Install Helm Chart
      run: |
        helm repo add myacr https://${{ secrets.ACR_SERVER }}
        helm install ping myacr/ping --namespace default
